[package]
name = "algorithmic_toolbox"
version = "0.0.1"
authors = ["Sergey Kacheev <uo0@ya.ru>"]
edition = "2021"

[dependencies]
num-bigint = "0.4.3"
num-traits = "0.2.15"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "fib_bench"
harness = false
